# Spring配置
spring:
  application:
    name: songList
  profiles:
    active: prod,prodDruid
#    active: dev,devDruid
amap:
  key: ed782194c3b3b3fffe146ae99e0dcdba
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8